// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLBm4NJlz7ZzgMnBa_zejeN1PB_rnZ6g',
    appId: '1:337138804324:web:9783569586b048bbe9e171',
    messagingSenderId: '337138804324',
    projectId: 'eldercare-cccf0',
    authDomain: 'eldercare-cccf0.firebaseapp.com',
    storageBucket: 'eldercare-cccf0.firebasestorage.app',
    measurementId: 'G-X2HCVW0P2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxsp5nj5_0se2uBTxk_8GrEgBBQn2uwRM',
    appId: '1:337138804324:android:3cc837c20b7174c2e9e171',
    messagingSenderId: '337138804324',
    projectId: 'eldercare-cccf0',
    storageBucket: 'eldercare-cccf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4VLLepxl0_7GpNNB53TvLInugtRg3gM',
    appId: '1:337138804324:ios:01646df6a7b0980ae9e171',
    messagingSenderId: '337138804324',
    projectId: 'eldercare-cccf0',
    storageBucket: 'eldercare-cccf0.firebasestorage.app',
    iosBundleId: 'com.example.elderCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4VLLepxl0_7GpNNB53TvLInugtRg3gM',
    appId: '1:337138804324:ios:01646df6a7b0980ae9e171',
    messagingSenderId: '337138804324',
    projectId: 'eldercare-cccf0',
    storageBucket: 'eldercare-cccf0.firebasestorage.app',
    iosBundleId: 'com.example.elderCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLBm4NJlz7ZzgMnBa_zejeN1PB_rnZ6g',
    appId: '1:337138804324:web:a8797c9c7e728600e9e171',
    messagingSenderId: '337138804324',
    projectId: 'eldercare-cccf0',
    authDomain: 'eldercare-cccf0.firebaseapp.com',
    storageBucket: 'eldercare-cccf0.firebasestorage.app',
    measurementId: 'G-2Y4N6YFMTH',
  );
}
